LKM 1 DATAMINING

NOFITA NUR AINI
222410101024


**1. Buatlah array 2D berikut menggunakan numpy**

In [ ]:
import numpy as np

arr = np.array([[4, 4, 5], [7, 6, 4], [9, 7, 4], [6, 3, 7]])
print(arr)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


**2. Buatlah array 3D berikut menggunakan numpy**

In [ ]:
import numpy as np
arr = np.array ([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],
                  [[2,1,2],[9,8,5],[3,7,3],[4,9,9]],
                  [[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])
print (arr)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


**3. Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut.**

In [ ]:
import numpy as np
arr = np.array ([[1,8,8,2],[8,2,1,2],[10,1,4,7],[1,4,7,8],[8,2,3,4]])
print ("Menampilkan array awal:")
print (arr)
arr [::2] += 1
print("Menampilkan array setelah penambahan angka +1 pada baris ganjil:")
print (arr)

arr [:, 1::2] +=2
print("Menampilkan hasil akhir array setelah kemudian ditambah angka +2 pada kolom genap:")
print (arr)

Menampilkan array awal:
[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]
Menampilkan array setelah penambahan angka +1 pada baris ganjil:
[[ 2  9  9  3]
 [ 8  2  1  2]
 [11  2  5  8]
 [ 1  4  7  8]
 [ 9  3  4  5]]
Menampilkan hasil akhir array setelah kemudian ditambah angka +2 pada kolom genap:
[[ 2 11  9  5]
 [ 8  4  1  4]
 [11  4  5 10]
 [ 1  6  7 10]
 [ 9  5  4  7]]


**4. Baliklah sumbu z array 3D berikut**

In [ ]:
import numpy as np
arr = np.array ([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],
                  [[2,1,2],[9,8,5],[3,7,3],[4,9,9]],
                  [[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])
print ("Array awal:")
print (arr)
print ("\n")
print ("Array setelah dibalik menjadi sumbu z:")
arr_flip = np.flip(arr, axis=2)
print(arr_flip)

Array awal:
[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


Array setelah dibalik menjadi sumbu z:
[[[ 5  8  7]
  [ 7  7  4]
  [ 9  1  7]
  [10  4  5]]

 [[ 2  1  2]
  [ 5  8  9]
  [ 3  7  3]
  [ 9  9  4]]

 [[ 3  9  2]
  [ 8  4  2]
  [ 6  6  1]
  [ 3  1  8]]]


**5. Ubahlah array pada soal 4 menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah reshape)**



In [ ]:
import numpy as np
arr = np.array([[[7,8,5], [4,7,7] ,[7,1,9], [5,4,10]],
                [[2,1,2], [9,8,5], [3,7,3], [4,9,9]],
                [[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])
arr_reshaped = arr.reshape(6, 6)
print ("Hasil array 2D berukuran 6x6 adalah:")
print(arr_reshaped)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]
Hasil array 2D berukuran 6x6 adalah:
[[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


**6. Ubahlah matriks kiri menjadi matriks sebelah kanan**

In [ ]:
import numpy as np
arr = np.array ([[5,10,10,7],
                 [7,8,4,10],
                 [9,10,2,5],
                 [1,8,9,3],
                 [6,10,5,2],
                 [4,6,9,4]])
arr1 = arr[:3,0:2]
arr2 = arr[3:6, 0:2]
arr3 = arr[:3,2:4]
arr4 = arr[3:6, 2:4]
mix1 = np.concatenate((arr4, arr2), axis=1)
mix2 = np.concatenate((arr3, arr1), axis=1)
hasil = np.concatenate((mix1, mix2), axis=0)

print('Indeks yang akan diambil per arraynya:')
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print("\n")
print("Matriks awal: \n{}".format(arr))
print("\n")
print("Matriks setelah diubah: \n{}".format(hasil))

Indeks yang akan diambil per arraynya:
[[ 5 10]
 [ 7  8]
 [ 9 10]]
[[ 1  8]
 [ 6 10]
 [ 4  6]]
[[10  7]
 [ 4 10]
 [ 2  5]]
[[9 3]
 [5 2]
 [9 4]]


Matriks awal: 
[[ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]
 [ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]]


Matriks setelah diubah: 
[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
